/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3.presentacion.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author maureen
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(85, 65, 118));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(64, 43, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        pnlClientes = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlOrdenTrabajo = new javax.swing.JPanel();
        lblOrdenTrabajo = new javax.swing.JLabel();
        pnlFichaTecnica = new javax.swing.JPanel();
        lblFichaTecnica = new javax.swing.JLabel();
        pnlMateriales = new javax.swing.JPanel();
        lblMateriales = new javax.swing.JLabel();
        pnlProveedores = new javax.swing.JPanel();
        lblProveedores = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlCiudad = new javax.swing.JPanel();
        lblCiudad = new javax.swing.JLabel();
        pnlPersona = new javax.swing.JPanel();
        lblPersona = new javax.swing.JLabel();
        pnlNorma = new javax.swing.JPanel();
        lblNorma = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlSide.setBackground(new java.awt.Color(54, 33, 89));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlClientes.setBackground(new java.awt.Color(85, 65, 118));
        pnlClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlClientesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlClientesMousePressed(evt);
            }
        });

        lblClientes.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 245, 245));
        lblClientes.setText("Clientes");

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSide.add(pnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 220, 40));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 245, 245));
        jLabel5.setText("Maquila Textil");
        pnlSide.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnlOrdenTrabajo.setBackground(new java.awt.Color(64, 43, 100));
        pnlOrdenTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlOrdenTrabajoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlOrdenTrabajoMousePressed(evt);
            }
        });

        lblOrdenTrabajo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblOrdenTrabajo.setForeground(new java.awt.Color(255, 245, 245));
        lblOrdenTrabajo.setText("Orden de Trabajo");

        javax.swing.GroupLayout pnlOrdenTrabajoLayout = new javax.swing.GroupLayout(pnlOrdenTrabajo);
        pnlOrdenTrabajo.setLayout(pnlOrdenTrabajoLayout);
        pnlOrdenTrabajoLayout.setHorizontalGroup(
            pnlOrdenTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenTrabajoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblOrdenTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlOrdenTrabajoLayout.setVerticalGroup(
            pnlOrdenTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdenTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrdenTrabajo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSide.add(pnlOrdenTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 40));

        pnlFichaTecnica.setBackground(new java.awt.Color(64, 43, 100));
        pnlFichaTecnica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlFichaTecnicaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlFichaTecnicaMousePressed(evt);
            }
        });

        lblFichaTecnica.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblFichaTecnica.setForeground(new java.awt.Color(255, 245, 245));
        lblFichaTecnica.setText("Ficha Técnica");

        javax.swing.GroupLayout pnlFichaTecnicaLayout = new javax.swing.GroupLayout(pnlFichaTecnica);
        pnlFichaTecnica.setLayout(pnlFichaTecnicaLayout);
        pnlFichaTecnicaLayout.setHorizontalGroup(
            pnlFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFichaTecnicaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblFichaTecnica, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlFichaTecnicaLayout.setVerticalGroup(
            pnlFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFichaTecnicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFichaTecnica)
                .addContainerGap())
        );

        pnlSide.add(pnlFichaTecnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 40));

        pnlMateriales.setBackground(new java.awt.Color(64, 43, 100));
        pnlMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMaterialesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMaterialesMouseEntered(evt);
            }
        });

        lblMateriales.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblMateriales.setForeground(new java.awt.Color(255, 245, 245));
        lblMateriales.setText("Materiales");

        javax.swing.GroupLayout pnlMaterialesLayout = new javax.swing.GroupLayout(pnlMateriales);
        pnlMateriales.setLayout(pnlMaterialesLayout);
        pnlMaterialesLayout.setHorizontalGroup(
            pnlMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlMaterialesLayout.setVerticalGroup(
            pnlMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMateriales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSide.add(pnlMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 40));

        pnlProveedores.setBackground(new java.awt.Color(64, 43, 100));
        pnlProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlProveedoresMouseEntered(evt);
            }
        });

        lblProveedores.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblProveedores.setForeground(new java.awt.Color(255, 245, 245));
        lblProveedores.setText("Proveedores");

        javax.swing.GroupLayout pnlProveedoresLayout = new javax.swing.GroupLayout(pnlProveedores);
        pnlProveedores.setLayout(pnlProveedoresLayout);
        pnlProveedoresLayout.setHorizontalGroup(
            pnlProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProveedoresLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlProveedoresLayout.setVerticalGroup(
            pnlProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProveedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSide.add(pnlProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, 40));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        pnlSide.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 10));

        pnlCiudad.setBackground(new java.awt.Color(64, 43, 100));
        pnlCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCiudadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCiudadMouseEntered(evt);
            }
        });

        lblCiudad.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblCiudad.setForeground(new java.awt.Color(255, 245, 245));
        lblCiudad.setText("Ciudad");

        javax.swing.GroupLayout pnlCiudadLayout = new javax.swing.GroupLayout(pnlCiudad);
        pnlCiudad.setLayout(pnlCiudadLayout);
        pnlCiudadLayout.setHorizontalGroup(
            pnlCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCiudadLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlCiudadLayout.setVerticalGroup(
            pnlCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCiudadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCiudad)
                .addContainerGap())
        );

        pnlSide.add(pnlCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 40));

        pnlPersona.setBackground(new java.awt.Color(64, 43, 100));
        pnlPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPersonaMouseEntered(evt);
            }
        });

        lblPersona.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblPersona.setForeground(new java.awt.Color(255, 245, 245));
        lblPersona.setText("Persona");

        javax.swing.GroupLayout pnlPersonaLayout = new javax.swing.GroupLayout(pnlPersona);
        pnlPersona.setLayout(pnlPersonaLayout);
        pnlPersonaLayout.setHorizontalGroup(
            pnlPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlPersonaLayout.setVerticalGroup(
            pnlPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPersonaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPersona)
                .addContainerGap())
        );

        pnlSide.add(pnlPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 40));

        pnlNorma.setBackground(new java.awt.Color(64, 43, 100));
        pnlNorma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNormaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNormaMouseEntered(evt);
            }
        });

        lblNorma.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblNorma.setForeground(new java.awt.Color(255, 245, 245));
        lblNorma.setText("Norma");

        javax.swing.GroupLayout pnlNormaLayout = new javax.swing.GroupLayout(pnlNorma);
        pnlNorma.setLayout(pnlNormaLayout);
        pnlNormaLayout.setHorizontalGroup(
            pnlNormaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNormaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblNorma, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlNormaLayout.setVerticalGroup(
            pnlNormaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNormaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNorma)
                .addContainerGap())
        );

        pnlSide.add(pnlNorma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 40));

        jPanel1.setBackground(new java.awt.Color(144, 4, 246));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 245, 245));
        jLabel3.setText("Usuario Administrador");

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 245, 245));
        jLabel4.setText("Sistema Textil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel4)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        lblSalir.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(54, 33, 89));
        lblSalir.setText("X");
        lblSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlSide, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSalir)
                        .addContainerGap())
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlSide, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void pnlClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_pnlClientesMousePressed

    private void pnlOrdenTrabajoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOrdenTrabajoMousePressed

    }//GEN-LAST:event_pnlOrdenTrabajoMousePressed

    private void pnlFichaTecnicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFichaTecnicaMousePressed

    }//GEN-LAST:event_pnlFichaTecnicaMousePressed

    private void pnlMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaterialesMouseClicked
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        setColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);

        pnlMaterial pMaterial = new pnlMaterial();
        pMaterial.setSize(400, 300);
        pMaterial.setLocation(5, 5);

        pnlContenedor.removeAll();
        pnlContenedor.add(pMaterial, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_pnlMaterialesMouseClicked

    private void pnlProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProveedoresMouseEntered
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        setColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);
    }//GEN-LAST:event_pnlProveedoresMouseEntered

    private void pnlCiudadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCiudadMouseEntered
        // TODO add your handling code here:
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        setColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);
    }//GEN-LAST:event_pnlCiudadMouseEntered

    private void pnlCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCiudadMouseClicked
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        setColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);
       
        pnlCiudad pCiudad= new pnlCiudad();
        pCiudad.setSize(400, 300);
        pCiudad.setLocation(5, 5);

        pnlContenedor.removeAll();
        pnlContenedor.add(pCiudad, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }//GEN-LAST:event_pnlCiudadMouseClicked

    private void pnlClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseClicked

        setColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);


    }//GEN-LAST:event_pnlClientesMouseClicked

    private void pnlPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPersonaMouseClicked
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        setColor(pnlPersona);
        resetColor(pnlNorma);

        pnlPersona pPersona = new pnlPersona();
        pPersona.setSize(400, 300);
        pPersona.setLocation(5, 5);

        pnlContenedor.removeAll();
        pnlContenedor.add(pPersona, BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();


    }//GEN-LAST:event_pnlPersonaMouseClicked

    private void pnlPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPersonaMouseEntered
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        setColor(pnlPersona);
        resetColor(pnlNorma);
    }//GEN-LAST:event_pnlPersonaMouseEntered

    private void pnlClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseEntered
        setColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);
    }//GEN-LAST:event_pnlClientesMouseEntered

    private void pnlOrdenTrabajoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOrdenTrabajoMouseEntered
        resetColor(pnlClientes);
        setColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);
    }//GEN-LAST:event_pnlOrdenTrabajoMouseEntered

    private void pnlFichaTecnicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFichaTecnicaMouseEntered
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        setColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);
    }//GEN-LAST:event_pnlFichaTecnicaMouseEntered

    private void pnlMaterialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMaterialesMouseEntered
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        setColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        resetColor(pnlNorma);
    }//GEN-LAST:event_pnlMaterialesMouseEntered

    private void pnlNormaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNormaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlNormaMouseClicked

    private void pnlNormaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNormaMouseEntered
        resetColor(pnlClientes);
        resetColor(pnlOrdenTrabajo);
        resetColor(pnlFichaTecnica);
        resetColor(pnlMateriales);
        resetColor(pnlProveedores);
        resetColor(pnlCiudad);
        resetColor(pnlPersona);
        setColor(pnlNorma);
    }//GEN-LAST:event_pnlNormaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblFichaTecnica;
    private javax.swing.JLabel lblMateriales;
    private javax.swing.JLabel lblNorma;
    private javax.swing.JLabel lblOrdenTrabajo;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JLabel lblProveedores;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JPanel pnlCiudad;
    private javax.swing.JPanel pnlClientes;
    public static javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlFichaTecnica;
    private javax.swing.JPanel pnlMateriales;
    private javax.swing.JPanel pnlNorma;
    private javax.swing.JPanel pnlOrdenTrabajo;
    private javax.swing.JPanel pnlPersona;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlProveedores;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
